name = "Impulsive Edition"
author = "EmeraldImpulse"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5aa5d08f782c889247e65832fc4fd125be0e680985b15bf5806866a4837ed62"

[versions]
fabric = "0.14.13"
minecraft = "1.19.3"

[options]
acceptable-game-versions = ["1.19.2", "1.19.3"]
