name = "Impulsive Edition"
author = "EmeraldImpulse"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "279c3649b4e866d35ca44f2dfe79fb97c37bbc08365d46dc929b23b8c94400fa"

[versions]
fabric = "0.14.13"
minecraft = "1.19.3"

[options]
acceptable-game-versions = ["1.19.2", "1.19.3"]
